global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    target_groups:
      - targets: ['prometheus.anna.local']

  - job_name: 'anna'
    target_groups:
      - targets: ['anna.anna.local']
